export const escolas = [
  {
    id: 0,
    cidade: "CACERES",
    escolas: [
      {
        id: 0,
        nome: "EE 12 DE OUTUBRO",
      },
      {
        id: 1,
        nome: "EE ANA MARIA",
      },
      {
        id: 2,
        nome: "EE DEMETRIO",
      },
      {
        id: 3,
        nome: "EE FREI AMBROSIO",
      },
      {
        id: 4,
        nome: "EE JOAO FLORENTINO",
      },
      {
        id: 5,
        nome: "EE LEOPOLDO AMBROSIO",
      },
      {
        id: 6,
        nome: "EE MARIO MOTTA",
      },
      {
        id: 7,
        nome: "EE MILTON MARQUES",
      },
      {
        id: 8,
        nome: "EE ONZE DE MARCO",
      },
      {
        id: 9,
        nome: "EE SÃO LUIZ",
      },
      {
        id: 10,
        nome: "EE TIRADENTES",
      },
      {
        id: 11,
        nome: "EE UNIAO E FORCA",
      },
    ],
  },
  {
    id: 1,
    cidade: "ARAPUTANGA",
    escolas: [
      {
        id: 0,
        nome: "EE JOAO SATO",
      },
      {
        id: 1,
        nome: "EE NOSSA SENHORA",
      },
      {
        id: 2,
        nome: "EE TANCREDO NEVES",
      },
    ],
  },
  {
    id: 2,
    cidade: "CURVELANDIA",
    escolas: [
      {
        id: 0,
        nome: "EE BOA ESPERANCA",
      },
    ],
  },
  {
    id: 3,
    cidade: "GLORIA D'OESTE",
    escolas: [
      {
        id: 0,
        nome: "EE JOSE BEJO",
      },
      {
        id: 1,
        nome: "EE RUI BARBOSA",
      },
    ],
  },
  {
    id: 4,
    cidade: "INDIAVAI",
    escolas: [
      {
        id: 0,
        nome: "EE PAULINO MODESTO",
      },
    ],
  },
  {
    id: 5,
    cidade: "LAMBARI",
    escolas: [
      {
        id: 0,
        nome: "EE PADRE JOSE ANCHIETA",
      },
    ],
  },
  {
    id: 6,
    cidade: "MIRASSOL",
    escolas: [
      {
        id: 0,
        nome: "EE 12 DE OUTUBRO",
      },
      {
        id: 1,
        nome: "EE BOA VISTA",
      },
      {
        id: 2,
        nome: "EE JOAO DE CAMPOS WIDAL",
      },
      {
        id: 3,
        nome: "EE MADRE CRISTINA",
      },
      {
        id: 4,
        nome: "EE PADRE JOSE DE ANCHIETA",
      },
      {
        id: 5,
        nome: "EE PADRE TIAGO",
      },
      {
        id: 6,
        nome: "EE PEDRO GALHARDO",
      },
    ],
  },
  {
    id: 7,
    cidade: "PORTO ESPERIDIAO",
    escolas: [
      {
        id: 0,
        nome: "EE 13 DE MAIO",
      },
      {
        id: 1,
        nome: "EE INDIGENA CHIQUITANO",
      },
      {
        id: 2,
        nome: "EE INDIGENA JOSE TURIBIO",
      },
      {
        id: 3,
        nome: "EE SAO GERALDO",
      },
    ],
  },
  {
    id: 8,
    cidade: "QUATRO MARCOS",
    escolas: [
      {
        id: 0,
        nome: "EE 15 DE JUNHO",
      },
      {
        id: 1,
        nome: "EE BENTO ALEXANDRE",
      },
      {
        id: 2,
        nome: "EE BERTOLDO FREIRE",
      },
      {
        id: 3,
        nome: "EE LOURENÇO PERUCHI",
      },
      {
        id: 4,
        nome: "EE MIGUEL BARBOSA",
      },
      {
        id: 5,
        nome: "EE SANTA ROSA",
      },
    ],
  },
  {
    id: 9,
    cidade: "RESERVA DO CABACAL",
    escolas: [
      {
        id: 0,
        nome: "EE DEMETRIO PEREIRA",
      },
    ],
  },
  {
    id: 10,
    cidade: "RIO BRANCO",
    escolas: [
      {
        id: 0,
        nome: "EE RANGEL TORRES",
      },
    ],
  },
  {
    id: 11,
    cidade: "SALTO DO CEU",
    escolas: [
      {
        id: 0,
        nome: "EE FRANCISCO VILLANOVA",
      },
      {
        id: 1,
        nome: "EE VILA PROGRESSO",
      },
    ],
  },
];

export const data2 = [
  {
    id: 1,
    cidade: "CACERES",
    escola: "EE UNIAO E FORCA",
    mes: "AGOSTO",
    enviou: "nao",
    linkPasta:
      "https://drive.google.com/drive/folders/14MO_4suhsOIsVspd7v1NmC2nsvs6W6OR",
    arquivos: [
      {
        nome: "mediacao_escolar_agosto_assinado-1.pdf",
        link: "https://drive.google.com/file/d/1489_ojMx0_M-SVStKuUc7T9w1qVeKU03/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 2,
    cidade: "CACERES",
    escola: "EE 12 DE OUTUBRO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1l2aF4YDdlRf_YSZ73N4rvG1IKsg5ZjVK",
    arquivos: [
      {
        nome: "Mediação escolar mês de agosto.pdf",
        link: "https://drive.google.com/file/d/1RubS701Vn1B9ubJV-Wt1FmA2qEorKzP2/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 3,
    cidade: "CACERES",
    escola: "EE ONZE DE MARCO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1OvkgRXwDwKqhhVlCfUL6b0BVbqkcP0Y7",
    arquivos: [
      {
        nome: "RELATÓRIO DE MÉDIAÇÃO-AGOSTO.pdf",
        link: "https://drive.google.com/file/d/1YksAD-Z7ld4rehq9ZBLU9qTLlZitXMcc/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Relatorio Mediação-Agosto.docx",
        link: "https://docs.google.com/document/d/1L55ofbAGYzVF9hlA_RDVRyDfaV2CoFt6/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 4,
    cidade: "CACERES",
    escola: "EE DEMETRIO",
    mes: "AGOSTO",
    enviou: "não",
    linkPasta:
      "https://drive.google.com/drive/folders/1ULglydIsiFjLSzZEpcsB2yK9UKPiTYK5",
    arquivos: [
      {
        nome: "relatório mediação agosto.docx",
        link: "https://docs.google.com/document/d/1h4WklsEJomP--cII4hOX-asnT5dRJS3y/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "CCF_000288.pdf",
        link: "https://drive.google.com/file/d/15fv3YMaoHQNbiOeGdp-oxtybwVbfl_Mt/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 5,
    cidade: "CACERES",
    escola: "EE MARIO MOTTA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1F295lHvjQd_CjDn9vL0i3GSIH4NQTO-_",
    arquivos: [
      {
        nome: "RELATÓRIO DE MEDIAÇÃO AGOSTO.docx",
        link: "https://docs.google.com/document/d/1VttVzZiCAI_wPNd9FXI5kqHsC0-p_qi8/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "RELATÓRIO MEDIAÇÃO escolaR AGOSTO.pdf",
        link: "https://drive.google.com/file/d/1C2wrPH8Yo8-2NMdC2tw4lu-rXztyQYTW/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 6,
    cidade: "CACERES",
    escola: "EE LEOPOLDO AMBROSIO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1ftH0AOw79TGT3xIpdVTxibe_gUR2aKTH",
    arquivos: [
      {
        nome: "relatorio AGOSTO DESCRITIVO atualizado (1).docx",
        link: "https://docs.google.com/document/d/13KV9qBxzrxNQB1g4uLc53HCH8bv0uTlL/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "Relatório mediação e ações agosto.pdf",
        link: "https://drive.google.com/file/d/1olHZQyrqspZsKsA-wHjB4S4nRTEOmXq_/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Relatório mediação e ações agosto.pdf",
        link: "https://drive.google.com/file/d/144MLFMO6ne_8V3xWt0tiWAhGXvL-uqTq/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 7,
    cidade: "CACERES",
    escola: "EE MILTON MARQUES",
    mes: "AGOSTO",
    enviou: "não",
    linkPasta:
      "https://drive.google.com/drive/folders/1MJfCRDoncR4UCHJAqtHYbIgznpiuUhI6",
    arquivos: [
      {
        nome: "Relatório de Mediação-Agosto.docx",
        link: "https://docs.google.com/document/d/1C3bv0VljrEOA3u3F5eSpsOCKATPMy0yG/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 8,
    cidade: "CACERES",
    escola: "EE ANA MARIA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1ym1crCzjdmx3lbime3iXl_pLYG9Ov9QA",
    arquivos: [
      {
        nome: "SCAN0000.PDF",
        link: "https://drive.google.com/file/d/11KGAJ6LIXtHKDQiH3twQE05CaaJ-joDb/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "lilás.pdf",
        link: "https://drive.google.com/file/d/1lIaqrSIcTM1eD6jEkH8TpgfAZ82lLSb1/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 9,
    cidade: "CACERES",
    escola: "EE TIRADENTES",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1JG89i_YS2p-bJkQchQX1EbR0MqVykjDr",
    arquivos: [
      {
        nome: "MEDIAÇÃO escolaR WORD - RELATORIO- AGOSTO EE NATALINO FERREIRA MENDES.docx",
        link: "https://docs.google.com/document/d/1mnhqiwCD2pCrCAdY4zZfwQJ4plzZtT9z/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "AGOSTO MEDIAÇÃO escolaR.pdf",
        link: "https://drive.google.com/file/d/1LpjeK3JBV0OFBTrXjAiT7oNR5bta8dV4/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 10,
    cidade: "CACERES",
    escola: "EE JOAO FLORENTINO",
    mes: "AGOSTO",
    enviou: "não",
    linkPasta:
      "https://drive.google.com/drive/folders/1Cb8Cv73JdR_1TJRJQ9lDFzaT5VZHiVQ6",
    arquivos: [
      {
        nome: "RELATÓRIO PROFESSOR JOÃO FLORENTINO-AGOSTO.pdf",
        link: "https://drive.google.com/file/d/1_Jtg5z6pHkQGuaanMSAFhTw_GKSSigli/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 11,
    cidade: "CACERES",
    escola: "EE SÃO LUIZ",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1TPYRFaITZZ75hv_OGmK0fjb6QMvQiz1j",
    arquivos: [
      {
        nome: "RELATORIO AGOSTO MEDIAÇÃO escolaR.pdf",
        link: "https://drive.google.com/file/d/1pDrdIucVgMT7JOoYBH9cv7rLvvMVF37q/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 12,
    cidade: "CACERES",
    escola: "EE FREI AMBROSIO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1LO4BFWT7MTQc2c3og1Jc8RDyi5HN02ln",
    arquivos: [
      {
        nome: "mediação agosto.pdf",
        link: "https://drive.google.com/file/d/1bvxmDaRhPlPzUa2bLW18A1hqzbY5md1V/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "RELATORIO  AGOSTO escola FREI AMBRÓSIO - Copia - Copia.docx",
        link: "https://docs.google.com/document/d/13kWFfPkHeN69naeo6vcsTAkPLLBUP-vb/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 13,
    cidade: "RESERVA DO CABACAL",
    escola: "EE DEMETRIO PEREIRA",
    mes: "AGOSTO",
    enviou: "não",
    linkPasta:
      "https://drive.google.com/drive/folders/1fkMfhFvXSi3VzgEuIHaGx5eXEpAXy4SW",
    arquivos: [
      {
        nome: "DRE-CAC-COGER -Relatório agosto 2024.docx",
        link: "https://docs.google.com/document/d/1VjRNQCX3dPqaosPz3aXjEgBgO5d4a1iQ/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 14,
    cidade: "PORTO ESPERIDIAO",
    escola: "EE SAO GERALDO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1DXUqE2hv9GP_olpKQZlknMvZ3ljAOOeo",
    arquivos: [
      {
        nome: "Relatório Agosto.docx",
        link: "https://docs.google.com/document/d/1iWT_BWBsMOJwfqbFKqDQ3_pwS6qU0MOp/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 15,
    cidade: "PORTO ESPERIDIAO",
    escola: "EE INDIGENA JOSE TURIBIO",
    mes: "AGOSTO",
    enviou: "Não",
    linkPasta:
      "https://drive.google.com/drive/folders/1Tzatf--cprRHVXiNiRQFW5RvrslXJNMI",
    arquivos: [],
  },
  {
    id: 16,
    cidade: "PORTO ESPERIDIAO",
    escola: "EE INDIGENA CHIQUITANO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1z3_GGVtmdaDMiZJmHINpXDiKobHENed9",
    arquivos: [
      {
        nome: "MEDIAÇÃO DO MÊS DE AGOSTO.docx",
        link: "https://docs.google.com/document/d/18pkWoJ0A_GKcZtbgV3TpOmCDkaHIBo-m/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "CamScanner 17-09-2024 10.11.pdf",
        link: "https://drive.google.com/file/d/1ZHoslYWuY4kpXScRaOzsYlWLINtgEPyO/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 17,
    cidade: "PORTO ESPERIDIAO",
    escola: "EE 13 DE MAIO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1HMoeE-hcKEYNviqMEqrhuYCnStyuiYjN",
    arquivos: [
      {
        nome: "MODELO DE RELATORIO- AGOSTO MEDIAÇÃO.docx",
        link: "https://docs.google.com/document/d/18P1OUjMoPz24LAKH0qlw2-uu2x4xmZso/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 18,
    cidade: "GLORIA D'OESTE",
    escola: "EE JOSE BEJO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/17dnmhukwQD1_23G3RlU2Lv99fvfuHqzJ",
    arquivos: [
      {
        nome: "RELATÓRIO BUSCA ATIVA- AGOSTO.docx",
        link: "https://docs.google.com/document/d/1WU4JpRNi2bbaCFkgOPML3Hi8YN-AXB0M/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "RELATORIO AGOSTO E.E.José Bejo.pdf",
        link: "https://drive.google.com/file/d/1-ZG-uwkTPklHGWL0lClHgilmc0hENCA_/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Relatório_mediação_José_Bejo_agosto.pdf",
        link: "https://drive.google.com/file/d/1eFTvZRdi4AYid37E7jQwu-sujmvG41Ew/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "RELATORIO AGOSTO E.E.José Bejo.docx",
        link: "https://docs.google.com/document/d/1j1bfToShiYwtyRo5kpCprQQOci6Fx0Wq/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 19,
    cidade: "GLORIA D'OESTE",
    escola: "EE RUI BARBOSA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1Zfb2pYWqwkcmV_vG6-mBlJ84Q2rvPVxx",
    arquivos: [
      {
        nome: "TABACO Video 2024-08-29 at 18.44.12.mp4",
        link: "https://drive.google.com/file/d/1RWEa_fSy_jEopo5B6Nh7JqMpVTXrDZnT/view?usp=drivesdk",
        tipo: "MP4",
      },
      {
        nome: "WhatsApp Video 2024-08-29 at 18.44.12.mp4",
        link: "https://drive.google.com/file/d/1JewzMwWnsoIuY_oedHQdI27atkpKeEwp/view?usp=drivesdk",
        tipo: "MP4",
      },
      {
        nome: "Rel Agosto RUI BARBOSA  - Coord. ALEXANDRA.pdf",
        link: "https://drive.google.com/file/d/1o1Kwo6lXqLmn4gJdrawITHtoAD-tRX2z/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "WhatsApp Image 2024-08-29 at 07.59.40.jpeg",
        link: "https://drive.google.com/file/d/1um8WSd2rbzZ9PPpuOnO1w0xibQ5I07lv/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "WhatsApp Image 2024-08-29 at 07.58.58.jpeg",
        link: "https://drive.google.com/file/d/1U-Mrb4yBcY3_0R5-ZkrIc9Ui8UAG3pDL/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "WhatsApp Image 2024-08-29 at 07.59.41.jpeg",
        link: "https://drive.google.com/file/d/1DdJiqEkw9ji4hwDC6PO4aB9svH3TaBOA/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "WhatsApp Image 2024-08-29 at 07.58.57(1).jpeg",
        link: "https://drive.google.com/file/d/1tHmmJ5V_Z3ofF0kcESASXpFYw3irg3ew/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "Post estudante.pdf",
        link: "https://drive.google.com/file/d/1e5snUdQqLA_YDFTCJJZjB5Rhwn0H_lh_/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Post 2 Agosto Lilás.pdf",
        link: "https://drive.google.com/file/d/1owjjLH4aZ0Qy49-qI1xBLfea4sgqUYkA/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Post para instagram de volta às aulas Rui Barbosa.pdf",
        link: "https://drive.google.com/file/d/1ufhhDYKSUZC9-qvUSl1azflNbFx6oq5M/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 20,
    cidade: "QUATRO MARCOS",
    escola: "EE BERTOLDO FREIRE",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/14tVSAKrphAqF2klFM9sabv3D34p6pCOr",
    arquivos: [
      {
        nome: "RELATÓRIO DE MEDIAÇÃO escolaR - AGOSTO.pdf",
        link: "https://drive.google.com/file/d/1pTlJDqECiOSTCRpNa4xKdCuSkR7VitDd/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Relatório Mediação mês de Agosto OK.docx",
        link: "https://docs.google.com/document/d/1ZuYPXawOsR5SD9zNY_va6XnvK3Cs9hwa/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 21,
    cidade: "QUATRO MARCOS",
    escola: "EE BENTO ALEXANDRE",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1kDeLTVGHCiUol6jxsvYuS8_OlTpJPGjC",
    arquivos: [
      {
        nome: "RELATÓRIO DE MEDIAÇÃO escolaR - AGOSTO.pdf",
        link: "https://drive.google.com/file/d/1VyEcg3dDTNW-oaOlQ7QokWzDjRi91v70/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "RELATORIO- AGOSTO MEDIAÇÃO EE Bento Alexandre para acesso aos link dos vídeos",
        link: "https://docs.google.com/document/d/1s67BtBKMrD-hWy6Fm-A2hqTzcAmQGuRU/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "RELATORIO- AGOSTO MEDIAÇÃO EE BENTO ALEXANDRE PARA ACESSO AOS LINK DOS VÍDEOS",
      },
      {
        nome: "Relatório mediação referente ao mês de Agosto com assinatura _",
        link: "https://drive.google.com/file/d/1xpT1z7JZ5ci7qUu5DCwssrGvPKCslwQM/view?usp=drivesdk",
        tipo: "RELATÓRIO MEDIAÇÃO REFERENTE AO MÊS DE AGOSTO COM ASSINATURA _",
      },
    ],
  },
  {
    id: 22,
    cidade: "QUATRO MARCOS",
    escola: "EE SANTA ROSA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1v8yiIeyS5Rm_h5ZEeKEobCk1oxTtQEdo",
    arquivos: [
      {
        nome: "DRE-CAC-COGER - Modelo de relatório Exp. VIOLENCIA DOMESTICA.pdf",
        link: "https://drive.google.com/file/d/1VxPpbDK8i8KthBGLEfRzDyPx7NKs5pEg/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "RELATÓRIO -VIOLENCIA DOMESTICA ",
        link: "https://drive.google.com/file/d/1vZRMqgjZLxKPrSeyOwkeVgKEma8llgR_/view?usp=drivesdk",
        tipo: "RELATÓRIO -VIOLENCIA DOMESTICA ",
      },
    ],
  },
  {
    id: 23,
    cidade: "QUATRO MARCOS",
    escola: "EE MIGUEL BARBOSA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1FasP1mwqJp6W7eqPNskfV_TUV7CwuviW",
    arquivos: [
      {
        nome: "relatorio agosto assinado e carimbado.pdf",
        link: "https://drive.google.com/file/d/14femnkbqvrCX5KAu2_MWB2DRimO0DTaa/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Relatório final de agosto.pdf",
        link: "https://drive.google.com/file/d/1TGgMcNHZt5fD6ogwQjFmdkYVOR8tx30D/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Relatório final de agosto.docx",
        link: "https://docs.google.com/document/d/1r5UIb7UoQl-GGaBIYik6PBE0q4j-bA7_/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "relatorio agosto assinado e carimbado.pdf",
        link: "https://drive.google.com/file/d/1cMtrTZ8sJ3TidWb49ay_pRLrl3H_GH0_/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "WhatsApp Video 2024-09-02 at 16.34.44.mp4",
        link: "https://drive.google.com/file/d/1ZQU4Vr7iEoBFzaNufyKZhISC3wPPxSlG/view?usp=drivesdk",
        tipo: "MP4",
      },
      {
        nome: "WhatsApp Video 2024-09-02 at 09.28.25 (2).mp4",
        link: "https://drive.google.com/file/d/1SS9ugfJdU35PDlU3RxXvQTd1kxtuwAOI/view?usp=drivesdk",
        tipo: "MP4",
      },
      {
        nome: "WhatsApp Image 2024-09-03 at 08.53.27.jpeg",
        link: "https://drive.google.com/file/d/1dL4VCbEi_aLokzvON8DPIskYEUAepU85/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "WhatsApp Image 2024-09-03 at 08.53.08.jpeg",
        link: "https://drive.google.com/file/d/1w2Ba8NTfn3brFgxOmRlbblWTnD1bXT_g/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "WhatsApp Image 2024-09-03 at 08.51.55.jpeg",
        link: "https://drive.google.com/file/d/1jxbo0YxSo6gtMVVG5OvX6FzHXdfDC9H0/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "WhatsApp Image 2024-09-03 at 08.51.29.jpeg",
        link: "https://drive.google.com/file/d/18EX3eOBogfG0EmgiTOD7E9Uq1t95dI14/view?usp=drivesdk",
        tipo: "JPEG",
      },
      {
        nome: "RELATORIO MEDIAÇÃO AGOSTO.pdf",
        link: "https://drive.google.com/file/d/1nFnOVtFDrZ7DlKXjEvvXmRV3CYvqBfCN/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 24,
    cidade: "QUATRO MARCOS",
    escola: "EE LOURENÇO PERUCHI",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1skUKGp1Oi8PWRqlVyDWVTvJ63ULS0dzn",
    arquivos: [
      {
        nome: "Orientativo agosto pdf.txt",
        link: "https://drive.google.com/file/d/1w0PnNUVVn0fkU0j_z7Nf-3UO-hMI6VDJ/view?usp=drivesdk",
        tipo: "TXT",
      },
      {
        nome: "Relatório Mediação Lei Maria da Penha.docx",
        link: "https://docs.google.com/document/d/1vIMdzofMGNre0_mG4QYUDGg20skE97oM/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 25,
    cidade: "QUATRO MARCOS",
    escola: "EE 15 DE JUNHO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1BuACXkpulYgwMk92sjWqBcSw_91_fqJr",
    arquivos: [
      {
        nome: "RELATÓRIO MEDIAÇÃO escolaR AGOSTO.docx",
        link: "https://docs.google.com/document/d/1Nt34xKaDYep3yJIk0GyzPQ_iDe4P8DpV/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 26,
    cidade: "INDIAVAI",
    escola: "EE PAULINO MODESTO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/188-U7wwyvVLdBKliR3aoQrsXyqGd5RUq",
    arquivos: [
      {
        nome: "RELATORIO de AGOSTO Mediação escolar Agosto Lilás.docx",
        link: "https://docs.google.com/document/d/1qa4PXGp2988xzxSvuz8aoP0YAowMA4Xk/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "vídeo agosto lilás.mp4",
        link: "https://drive.google.com/file/d/1MHlE8hGy_aNJn0laMx4HUR-5ZSfwzGKq/view?usp=drivesdk",
        tipo: "MP4",
      },
    ],
  },
  {
    id: 27,
    cidade: "ARAPUTANGA",
    escola: "EE TANCREDO NEVES",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1Hsawx05MTf4leZfdVFTfxevQobCIl8FB",
    arquivos: [
      {
        nome: "RELATORIO AGOSTO E.E.Pres. Tancredo de A. Neves - Oficial.docx",
        link: "https://docs.google.com/document/d/1wa5w3eWcxdeTE_oTg-yWX09gtPcI3aQ3/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 28,
    cidade: "ARAPUTANGA",
    escola: "EE NOSSA SENHORA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1eQM-So3wBY1XLH8DpIvHHl_g6s62AE1P",
    arquivos: [
      {
        nome: "RELATORIO de agosto.docx",
        link: "https://docs.google.com/document/d/1MQyvXAlmDkXN2BFUZEN153TAoFrQlozl/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "RELATORIO de agosto.pdf",
        link: "https://drive.google.com/file/d/12NQ_xlEQItwud4tgfO0lee-KLuiTY9HE/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 29,
    cidade: "ARAPUTANGA",
    escola: "EE JOAO SATO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1gpz3wD0PggupO-sAF7suOo6vKzf73Cmr",
    arquivos: [
      {
        nome: "RELATORIO MEDIAÇÃO escolaR AGOSTO LILAS.docx",
        link: "https://docs.google.com/document/d/1_Si4Uoc0TkyW-z9y6RkRduaqMaGM5yS1/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "relatorio agosto mediação.pdf",
        link: "https://drive.google.com/file/d/1CmiuiaUox2K3bEKtdJBULtnFDJzWS_ge/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 30,
    cidade: "RIO BRANCO",
    escola: "EE RANGEL TORRES",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1xc4dsEwo1UBXJ51cnzfnmiutV8BCrjr9",
    arquivos: [
      {
        nome: "RELATÓRIO AGOSTO LILAS 24.docx",
        link: "https://docs.google.com/document/d/1eNZXzegbJOuyh8wleLOW-dUYCTlVYuFk/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "RELATÓRIO AGOSTO LILAS 24.pdf",
        link: "https://drive.google.com/file/d/1165Dj4Dlb3P0nIOS4qfz-DWSjaCanxDG/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 31,
    cidade: "SALTO DO CEU",
    escola: " EE FRANCISCO VILLANOVA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1m9HKH9lDZJvsqgcfLLTumdYDCYATBKXu",
    arquivos: [
      {
        nome: "relatorio mediação agosto.docx",
        link: "https://docs.google.com/document/d/1d31GQ_wZ5wR_ukamG-ycYBb4hGQbHfjC/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 32,
    cidade: "SALTO DO CEU",
    escola: "EE VILA PROGRESSO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1IGf4Exjuo26072t3jEEE6Lo9xlYrpScu",
    arquivos: [
      {
        nome: "RELATÓRIO - AGOSTO VILLA PROGRESSO-escola CAMPO.pdf",
        link: "https://drive.google.com/file/d/1LHs93FGWLwWeofkGibtgcKUTo5QM1Ow3/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 33,
    cidade: "MIRASSOL",
    escola: "EE PEDRO GALHARDO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1TeTPIhEhx3YQ7JU8CjcPfQAUPFMhuZkQ",
    arquivos: [
      {
        nome: "MEDIAÇÃO escolaR AGOSTO.pdf",
        link: "https://drive.google.com/file/d/1_N4gKhea3kt6lmRdIaL4gyFKYzzRqtyM/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 34,
    cidade: "MIRASSOL",
    escola: "EE JOAO DE CAMPOS WIDAL",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1arhC0q_A3BSAahsT3yWNOEtTGTZ6z95a",
    arquivos: [
      {
        nome: "Relatorio Maria Penha 1.pdf",
        link: "https://drive.google.com/file/d/1K4YgpdPwB5e1ICC5s0M5XYOOVqMYvxCM/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "RELATORIO MARIA DA PENHA.docx",
        link: "https://docs.google.com/document/d/14Kg9pCGXtbTw2YCHf136Wa-EncbVl2U-/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "RELATORIO Infancia.docx",
        link: "https://docs.google.com/document/d/1Er7RnwS9jSISbTUHwQJxymgN5Cxbb8sG/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 35,
    cidade: "MIRASSOL",
    escola: "EE PADRE JOSE DE ANCHIETA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/10IvO2Jf86AlxkFiz1xcxZsfSfDhLYSs7",
    arquivos: [
      {
        nome: "orientativo Agosto (2).docx",
        link: "https://docs.google.com/document/d/1hw-elD8_JLJ38ZhfOBgcOyYQnrDNT6CD/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "orientativo Agosto 01.pdf",
        link: "https://drive.google.com/file/d/1dZtF_0O_M7E7k_tz9vJw89p8Mah9MG_i/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Orientativo Agosto PDF.pdf",
        link: "https://drive.google.com/file/d/1m-DkQPAhSql4Za2vhTVAd6dMh6XXl2xo/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 36,
    cidade: "MIRASSOL",
    escola: "EE 12 DE OUTUBRO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1NZnsyfahSgli3hQFdWA4IaR_w0TSFxyQ",
    arquivos: [
      {
        nome: "AGOSTO DIA DO ESTUDANTE.pdf",
        link: "https://drive.google.com/file/d/10Tz6IqXdHFPjgXtjmkLmAmRZutEgqWkk/view?usp=drivesdk",
        tipo: "PDF",
      },
      {
        nome: "Agosto lei maria da penha.pdf",
        link: "https://drive.google.com/file/d/1SSP6zzjjCg1cL-n9OyTRAcLcLoJiDSFO/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 37,
    cidade: "MIRASSOL",
    escola: "EE PADRE TIAGO",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/149H-NMP_oGg_W0wmlqT5VoGvA31xIT-i",
    arquivos: [
      {
        nome: "RELATORIO DO MÊS DE AGOSTO LILÁS.docx",
        link: "https://docs.google.com/document/d/1rOw6ttCtzKTOjUxft10oW7f5NDwZWH1E/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 38,
    cidade: "MIRASSOL",
    escola: "EE MADRE CRISTINA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/10aEgBLBMCC_V2rEKgyz1znTlkTSz0uVU",
    arquivos: [
      {
        nome: "MODELO DE RELATORIO-  AGOSTO  MEDIAÇÃO.docx",
        link: "https://docs.google.com/document/d/1kjExT65B_QCc1_7-8GCKpgeHU3GosNul/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
    ],
  },
  {
    id: 39,
    cidade: "MIRASSOL",
    escola: "EE BOA VISTA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/156LozZHP47qcs33imoTPBLoMqKHLJM5y",
    arquivos: [
      {
        nome: "E.E Boa Vista.docx",
        link: "https://docs.google.com/document/d/1zWg-4aizTNp4pMM36pvzCbjqdJ7A3pno/edit?usp=drivesdk&ouid=116700202092119734003&rtpof=true&sd=true",
        tipo: "DOCX",
      },
      {
        nome: "E. E. Boa Vista - Agosto.pdf",
        link: "https://drive.google.com/file/d/1RVmhrjiPZJTWLaP2KwNLKuwj6IYVwiGH/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 40,
    cidade: "LAMBARI",
    escola: "EE PADRE JOSE ANCHIETA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1ENQW-XQzm-2klfAj_gfHpvrGbLKSG5il",
    arquivos: [
      {
        nome: "Relatório mês de agosto.pdf",
        link: "https://drive.google.com/file/d/1YKKEVxn6N7RHHBcjgW4BjpZK1Dyf05ks/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
  {
    id: 41,
    cidade: "CURVELANDIA",
    escola: "EE BOA ESPERANCA",
    mes: "AGOSTO",
    enviou: "Sim",
    linkPasta:
      "https://drive.google.com/drive/folders/1GMVkXl8dezKIh11iQpe6vApMzbff6-Iu",
    arquivos: [
      {
        nome: "BRN3C2AF4EC06A1_021344.pdf",
        link: "https://drive.google.com/file/d/19vRGmDdhApPk78Ittc_2rUnQRCL_G0la/view?usp=drivesdk",
        tipo: "PDF",
      },
    ],
  },
];

export const contatos = [
  {
    cidade: "CÁCERES",
    escola: "EE DR.LEOPOLDO AMBRÓSIO FILHO",
    funcao: "DIRETOR",
    nome: "Edileuza da Silva Oliveira Antoniassi ",
    contato: "(65) 99614 0771",
    email: "edileuza.oliveira@edu.mt.gov.br",
    email_escola: "escola.11630@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE DR.LEOPOLDO AMBRÓSIO FILHO",
    funcao: "SECRETÁRIO",
    nome: "Alessandra de Paula Ferreira",
    contato: "(65) 99685 1978",
    email: "alessandra-paula.ferreira@edu.mt.gov.br",
    email_escola: "escola.11630@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE DR.LEOPOLDO AMBRÓSIO FILHO",
    funcao: "COORDENADOR",
    nome: "Pedro Thiago Lopes Rodrigues ",
    contato: "(65) 99308 4602",
    email: "pedro.rodrigues@edu.mt.gov.br",
    email_escola: "escola.11630@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE 12 DE OUTUBRO",
    funcao: "DIRETOR",
    nome: "Maria José de Oliveira Godoi ",
    contato: "(65) 99945 5620",
    email: "maria.godoi@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE 12 DE OUTUBRO",
    funcao: "SECRETÁRIO",
    nome: "Flávio Luiz Silva Paes ",
    contato: "(65) 99965 2370",
    email: "flavio.paes@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE 12 DE OUTUBRO",
    funcao: "COORDENADOR",
    nome: "Jennifer Bianca Leite dos Santos",
    contato: "(65) 99997 1395",
    email: "jennifer.santos@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE JOÃO FLORENTINO DA SILVA NETO",
    funcao: "DIRETOR",
    nome: "Robson José Faustino ",
    contato: "(65) 99623 1880",
    email: "robson.faustino@edu.mt.gov.br",
    email_escola: "escola.84336@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE JOÃO FLORENTINO DA SILVA NETO",
    funcao: "SECRETÁRIO",
    nome: "Jéssica Nunes de Oliveira",
    contato: "(65) 99610 0342",
    email: "jessica.nunes@edu.mt.gov.br",
    email_escola: "escola.84336@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE JOÃO FLORENTINO DA SILVA NETO",
    funcao: "COORDENADOR",
    nome: "Dirlei Carpejani de Jesus ",
    contato: "(65) 99661 1161",
    email: "dirlei.jesus@edu.mt.gov.br",
    email_escola: "escola.84336@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE JOÃO FLORENTINO DA SILVA NETO",
    funcao: "COORDENADOR",
    nome: "Sandra Prudencio Ivanhez",
    contato: "(65) 99636 3215",
    email: "sandra.ivanhez@edu.mt.gov.br",
    email_escola: "escola.84336@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE CÍVICO MILITAR SENADOR MÁRIO MOTTA",
    funcao: "DIRETOR",
    nome: "Addison Ricardo Fischer Corrêa ",
    contato: "(65) 99843 0850",
    email: "addison.correa@edu.mt.gov.br",
    email_escola: "escola.11614@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE CÍVICO MILITAR SENADOR MÁRIO MOTTA",
    funcao: "SECRETÁRIO",
    nome: "Grasiele Donatoni",
    contato: "(65) 99905 8425",
    email: "grasiele.donatoni@edu.mt.gov.br",
    email_escola: "escola.11614@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE CÍVICO MILITAR SENADOR MÁRIO MOTTA",
    funcao: "COORDENADOR",
    nome: "Ana Paula Lima Alfaia Bueno",
    contato: "(65) 99650 0070",
    email: "ana.alfaia@edu.mt.gov.br",
    email_escola: "escola.11614@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE CÍVICO MILITAR SENADOR MÁRIO MOTTA",
    funcao: "COORDENADOR",
    nome: "Eliane Nascimento Faria Gama ",
    contato: "(65) 99989 3256",
    email: "eliane.gama@edu.mt.gov.br",
    email_escola: "escola.11614@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE CÍVICO MILITAR SENADOR MÁRIO MOTTA",
    funcao: "COORDENADOR",
    nome: "Silvânia Maria de Souza Pereira ",
    contato: "(65) 99933 1240",
    email: "silvania.pereira@edu.mt.gov.br",
    email_escola: "escola.11614@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROF DEMÉTRIO COSTA PEREIRA",
    funcao: "DIRETOR",
    nome: "Regis Aparecido de Oliveira",
    contato: "(65) 99943 1668",
    email: "regis.oliveira@edu.mt.gov.br",
    email_escola: "escola.11703@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROF DEMÉTRIO COSTA PEREIRA",
    funcao: "SECRETÁRIO",
    nome: "Danielle Conceição de Almeida Santos ",
    contato: "(65) 99641 7373",
    email: "danielle.almeida@edu.mt.gov.br",
    email_escola: "escola.11703@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROF DEMÉTRIO COSTA PEREIRA",
    funcao: "COORDENADOR",
    nome: "Marisa Farias dos Santos",
    contato: "(65) 99909 1511",
    email: "marisa.lima@edu.mt.gov.br",
    email_escola: "escola.11703@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROF DEMÉTRIO COSTA PEREIRA",
    funcao: "COORDENADOR",
    nome: "Gisele Faria da Rocha",
    contato: "(65) 99623 5992",
    email: "gisele.rocha@edu.mt.gov.br",
    email_escola: "escola.11703@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROFª ANA MARIA",
    funcao: "DIRETOR",
    nome: "Carlos Alberto de Almeida Quintans ",
    contato: "(65) 98417 2001",
    email: "carlos.quintans@edu.mt.gov.br",
    email_escola: "escola.11797@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROFª ANA MARIA",
    funcao: "SECRETÁRIO",
    nome: "Denilson Ribeiro de Carvalho ",
    contato: "(65) 99662 2480",
    email: "denilson.carvalho@edu.mt.gov.br",
    email_escola: "escola.11797@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROFª ANA MARIA",
    funcao: "COORDENADOR",
    nome: "Anaildes Queiroz Rocha",
    contato: "(94) 99123 0151",
    email: "anaildes.rocha@edu.mt.gov.br",
    email_escola: "escola.11797@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROFª ANA MARIA",
    funcao: "COORDENADOR",
    nome: "Robson Cézar Hurtado",
    contato: "(65) 99614 0872",
    email: "robson.hurtado@edu.mt.gov.br",
    email_escola: "escola.11797@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE PROFª ANA MARIA",
    funcao: "COORDENADOR",
    nome: "Valtemir Araujo Pereira",
    contato: "(65) 99942 1435",
    email: "valtemir.pereira@edu.mt.gov.br",
    email_escola: "escola.11797@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE MILTOM MARQUES",
    funcao: "DIRETOR",
    nome: "Claudinéia Marinho das Flores ",
    contato: "(65) 99925 6039",
    email: "claudineia.flores@edu.mt.gov.br",
    email_escola: "escola.212490@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE MILTOM MARQUES",
    funcao: "SECRETÁRIO",
    nome: "Luizmar Deluque",
    contato: "(65) 99973 7636",
    email: "luizmar.deluque@edu.mt.gov.br",
    email_escola: "escola.212490@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE MILTOM MARQUES",
    funcao: "COORDENADOR",
    nome: "Anastácia da Cruz Moraes Alvares",
    contato: "(65) 99920 1150",
    email: "anastacia.alvares@edu.mt.gov.br",
    email_escola: "escola.212490@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE MILTOM MARQUES",
    funcao: "COORDENADOR",
    nome: "Jussara Cebalho",
    contato: "(65) 99223 6917",
    email: "jussara.cebalho@edu.mt.gov.br",
    email_escola: "escola.212490@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE TIRADENTES",
    funcao: "DIRETOR",
    nome: "Paulo Pinto do Nascimento Jatobá",
    contato: "(65) 99989 8863",
    email: "paulo.jatoba@edu.mt.gov.br",
    email_escola: "escola.61298@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE TIRADENTES",
    funcao: "SECRETÁRIO",
    nome: "Mery Ellen de Campos Pessoa",
    contato: "(65) 99677 8681",
    email: "mery.pessoa@edu.mt.gov.br",
    email_escola: "escola.61298@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE TIRADENTES",
    funcao: "COORDENADOR",
    nome: "Dionila Gomes Tavares",
    contato: "(65) 99618 6669",
    email: "dionila.tavares@edu.mt.gov.br",
    email_escola: "escola.61298@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE TIRADENTES",
    funcao: "COORDENADOR",
    nome: "Luana dos Santos Nogueira Garcia ",
    contato: "(65) 99671 4350",
    email: "luana.nogueira@edu.mt.gov.br",
    email_escola: "escola.61298@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE TIRADENTES",
    funcao: "COORDENADOR",
    nome: "Luzia Pinto de Araujo",
    contato: "(65) 99995 1201",
    email: "luzia.araujo@edu.mt.gov.br",
    email_escola: "escola.61298@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE FREI AMBRÓSIO",
    funcao: "DIRETOR",
    nome: "Patrícia Ramos B. de Sena Santos",
    contato: "(65) 99936 5366",
    email: "patricia.sena@edu.mt.gov.br",
    email_escola: "escola.11690@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE FREI AMBRÓSIO",
    funcao: "SECRETÁRIO",
    nome: "Paulo Henrique de Brito",
    contato: "(65) 99602 1944",
    email: "paulo-henrique.brito@edu.mt.gov.br",
    email_escola: "escola.11690@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE FREI AMBRÓSIO",
    funcao: "COORDENADOR",
    nome: "José Adriano de Miranda Pinto",
    contato: "(65) 99900 4455",
    email: "jose.pinto@edu.mt.gov.br",
    email_escola: "escola.11690@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE FREI AMBRÓSIO",
    funcao: "COORDENADOR",
    nome: "Silvana de Oliveira Zago",
    contato: "(65) 99957 9785",
    email: "silvana.zago@edu.mt.gov.br",
    email_escola: "escola.11690@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE SÃO LUIZ",
    funcao: "DIRETOR",
    nome: "Catarina da Silva ",
    contato: "(65) 99696 2544",
    email: "catarina.silva@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE SÃO LUIZ",
    funcao: "SECRETÁRIO",
    nome: "Eliebi Domingues Cardoso Bueno ",
    contato: "(65) 99608 4892",
    email: "eliebi.bueno@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE SÃO LUIZ",
    funcao: "COORDENADOR",
    nome: "Azenilda Pereira de Oliveira ",
    contato: "(65) 99617 1347",
    email: "azenilda.oliveira@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE SÃO LUIZ",
    funcao: "COORDENADOR",
    nome: "Ana Cláudia Rocha Cabral",
    contato: "(67) 99639 3850 ",
    email: "ana-claudia.cabral@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE SÃO LUIZ",
    funcao: "COORDENADOR",
    nome: "Valdiceia Moreira Ribeiro",
    contato: "(65) 99965-4301",
    email: "valdiceia.ribeiro@edu.mt.gov.br",
    email_escola: "escola.11657@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE UNIÃO E FORÇA",
    funcao: "DIRETOR",
    nome: "Elaine Fernanda Martins Mamoré",
    contato: "(65) 99910 1509",
    email: "elaine.mamore@edu.mt.gov.br",
    email_escola: "escola.11720@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE UNIÃO E FORÇA",
    funcao: "SECRETÁRIO",
    nome: "Ivonete Kusther Preisigke Furtado ",
    contato: "(65) 99945 8304",
    email: "ivonete.furtado@edu.mt.gov.br",
    email_escola: "escola.11720@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE UNIÃO E FORÇA",
    funcao: "COORDENADOR",
    nome: "Erika Patrícia Lacerda Dias Souza",
    contato: "(65) 99943 3990 ",
    email: "erika.souza@edu.mt.gov.br",
    email_escola: "escola.11720@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE UNIÃO E FORÇA",
    funcao: "COORDENADOR",
    nome: "Josilaine Rocha de Queirós Amorim",
    contato: "(65) 98439 7336",
    email: "josilaine.queiros@edu.mt.gov.br",
    email_escola: "escola.11720@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE UNIÃO E FORÇA",
    funcao: "COORDENADOR",
    nome: "Juciara Rodrigues Souza",
    contato: "(65) 999316232",
    email: "juciara.zattar@edu.mt.gov.br",
    email_escola: "escola.11720@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE ONZE DE MARÇO",
    funcao: "DIRETOR",
    nome: "Aline Silva de Assis",
    contato: "(66) 99672 6353",
    email: "aline.assis@edu.mt.gov.br",
    email_escola: "escola.11606@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE ONZE DE MARÇO",
    funcao: "SECRETÁRIO",
    nome: "Renato Augusto Lima Alfaia",
    contato: "(65) 99618 4321",
    email: "renato.alfaia@edu.mt.gov.br",
    email_escola: "escola.11606@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE ONZE DE MARÇO",
    funcao: "COORDENADOR",
    nome: "Ivete de Oliveira Espacini dos Reis",
    contato: "(65) 99641 1600",
    email: "ivete.reis@edu.mt.gov.br",
    email_escola: "escola.11606@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE ONZE DE MARÇO",
    funcao: "COORDENADOR",
    nome: "Jozivaldo Alves Martins ",
    contato: "(65) 99914 5499",
    email: "jozivaldo.martins@edu.mt.gov.br",
    email_escola: "escola.11606@edu.mt.gov.br",
  },
  {
    cidade: "CÁCERES",
    escola: "EE ONZE DE MARÇO",
    funcao: "COORDENADOR",
    nome: "Moisés Pereira Mendes",
    contato: "(65) 99918 8341",
    email: "moises.mendes@edu.mt.gov.br",
    email_escola: "escola.11606@edu.mt.gov.br",
  },
  {
    cidade: "CURVELÂNDIA",
    escola: "EE BOA ESPERANÇA",
    funcao: "DIRETOR",
    nome: "Aparecida Mendes Barbalho",
    contato: "(65) 99939 8070",
    email: "aparecida.barbalho@edu.mt.gov.br",
    email_escola: "escola.69493@edu.mt.gov.br",
  },
  {
    cidade: "CURVELÂNDIA",
    escola: "EE BOA ESPERANÇA",
    funcao: "SECRETÁRIO",
    nome: "Tania Cleia Silveira Fernandes ",
    contato: "(65) 98408 8123",
    email: "tania.fernandes@edu.mt.gov.br",
    email_escola: "escola.69493@edu.mt.gov.br",
  },
  {
    cidade: "CURVELÂNDIA",
    escola: "EE BOA ESPERANÇA",
    funcao: "COORDENADOR",
    nome: "Darci  Alves de Souza",
    contato: "(65) 98466 0507",
    email: "darci.souza@edu.mt.gov.br",
    email_escola: "escola.69493@edu.mt.gov.br",
  },
  {
    cidade: "CURVELÂNDIA",
    escola: "EE BOA ESPERANÇA",
    funcao: "COORDENADOR",
    nome: "Janaína Montanha Freire Penha",
    contato: "(65) 99924-3221",
    email: "janaina.penha@edu.mt.gov.br",
    email_escola: "escola.69493@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PEDRO GALHARDO GARCIA",
    funcao: "DIRETOR",
    nome: "Aline Karen Damacena ",
    contato: "(65) 99933 1282",
    email: "aline.damacena@edu.mt.gov.br",
    email_escola: "escola.16233@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PEDRO GALHARDO GARCIA",
    funcao: "SECRETÁRIO",
    nome: "Divaldo Carlos Cerqueira Júnior ",
    contato: "(65) 99915 0086",
    email: "divaldo.cerqueira@edu.mt.gov.br",
    email_escola: "escola.16233@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PEDRO GALHARDO GARCIA",
    funcao: "COORDENADOR",
    nome: "Elaine Cassia da Silva ",
    contato: "(65) 99606 0123",
    email: "elaine-cassia.silva@edu.mt.gov.br",
    email_escola: "escola.16233@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PEDRO GALHARDO GARCIA",
    funcao: "COORDENADOR",
    nome: "Gleici Simone Faneli do Nascimento",
    contato: "(65) 99904 2946 ",
    email: "gleici.nascimento@edu.mt.gov.br",
    email_escola: "escola.16233@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE BOA VISTA",
    funcao: "DIRETOR",
    nome: "Adriano Luis Babinski",
    contato: "(66) 99968 5238",
    email: "adriano.babinski@edu.mt.gov.br",
    email_escola: "escola.16284@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE BOA VISTA",
    funcao: "SECRETÁRIO",
    nome: "Fabiane dos Santos Cintra Ferreira ",
    contato: "(65) 99929 6725",
    email: "fabiane.cintra@edu.mt.gov.br",
    email_escola: "escola.16284@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE BOA VISTA",
    funcao: "COORDENADOR",
    nome: "Amilton Flávio Coleta Leal ",
    contato: "(65) 99615 5159",
    email: "amilton.leal@edu.mt.gov.br",
    email_escola: "escola.16284@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE 12 DE OUTUBRO",
    funcao: "DIRETOR",
    nome: "José Humberto Veríssimo Zuchetti ",
    contato: "(65) 99961 4213",
    email: "jose.zuchetti@edu.mt.gov.br",
    email_escola: "escola.16187@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE 12 DE OUTUBRO",
    funcao: "SECRETÁRIO",
    nome: "Claudia Lucia Pinto ",
    contato: "(65) 99938 2108",
    email: "claudia.pinto@edu.mt.gov.br",
    email_escola: "escola.16187@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE 12 DE OUTUBRO",
    funcao: "COORDENADOR",
    nome: "Márcia Franco de Carvalho",
    contato: "(65) 99911 7917",
    email: "marcia.carvalho@edu.mt.gov.br",
    email_escola: "escola.16187@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE 12 DE OUTUBRO",
    funcao: "COORDENADOR",
    nome: "Paula Rhischelle Rodrigues ",
    contato: "(65) 99984 6405",
    email: "paula.rodrigues@edu.mt.gov.br",
    email_escola: "escola.16187@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE MADRE CRISTINA",
    funcao: "DIRETOR",
    nome: "Lucas Andre Simione",
    contato: "(65) 99916 1611",
    email: "lucas.simione@edu.mt.gov.br",
    email_escola: "escola.94420@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE MADRE CRISTINA",
    funcao: "SECRETÁRIO",
    nome: "Marlene Aparecida",
    contato: "(65) 99938 5671",
    email: "clebson.silva@edu.mt.gov.br",
    email_escola: "escola.94420@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE JOSÉ DE ANCHIETA",
    funcao: "DIRETOR",
    nome: "Josimar de Aquino",
    contato: "(65) 99613 0197",
    email: "josimar.aquino@edu.mt.gov.br",
    email_escola: "escola.16241@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE JOSÉ DE ANCHIETA",
    funcao: "SECRETÁRIO",
    nome: "Flavio Ferrai dos Santos",
    contato: "(65) 99614 5939",
    email: "flavio.ferrai@edu.mt.gov.br",
    email_escola: "escola.16241@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE JOSÉ DE ANCHIETA",
    funcao: "COORDENADOR",
    nome: "Eva Alves do Nascimento Silva",
    contato: "(65) 99977 1912",
    email: "eva.nascimento@edu.mt.gov.br",
    email_escola: "escola.16241@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE JOÃO CAMPOS WINDAL",
    funcao: "DIRETOR",
    nome: "Geani de Cassia Rodrigues ",
    contato: "(65) 99646 3469",
    email: "geani.rodrigues@edu.mt.gov.br",
    email_escola: "escola.16195@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE JOÃO CAMPOS WINDAL",
    funcao: "SECRETÁRIO",
    nome: "Clebson Rodrigues da Silva ",
    contato: "(65) 99637 7346",
    email: "escola.16241@edu.mt.gov.br",
    email_escola: "escola.16195@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE JOÃO CAMPOS WINDAL",
    funcao: "COORDENADOR",
    nome: "Rosa Tereza Gomes da Silva Miler",
    contato: "(65) 99922 1079",
    email: "rosa.gomes@edu.mt.gov.br",
    email_escola: "escola.16195@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE TIAGO",
    funcao: "DIRETOR",
    nome: "Giancarlo Marinho Costa",
    contato: "(65) 99994 5626",
    email: "giancarlo.costa@edu.mt.gov.br",
    email_escola: "escola.16209@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE TIAGO",
    funcao: "SECRETÁRIO",
    nome: "Michael Sulivan",
    contato: "(65) 99635 7299",
    email: "rosana.spolador@edu.mt.gov.br",
    email_escola: "escola.16209@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE TIAGO",
    funcao: "COORDENADOR",
    nome: "Érica dos Reis de S. Ribeiro",
    contato: "(65) 99945 2674",
    email: "erica.souza@edu.mt.gov.br",
    email_escola: "escola.16209@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE TIAGO",
    funcao: "COORDENADOR",
    nome: "Ana Paula Rodrigues de Souza ",
    contato: "(65) 99905 6392",
    email: "ana-paula.rodrigues@edu.mt.gov.br",
    email_escola: "escola.16209@edu.mt.gov.br",
  },
  {
    cidade: "MIRASSOL D'OESTE",
    escola: "EE PADRE TIAGO",
    funcao: "COORDENADOR",
    nome: "Daliane Cristina Barreto Lourenção",
    contato: "(65) 99907 4780",
    email: "daliane.lourencao@edu.mt.gov.br",
    email_escola: "escola.16209@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE SANTA ROSA",
    funcao: "DIRETOR",
    nome: "Simone Guedes Peres Marim",
    contato: "(65) 99907 8373",
    email: "simone.marim@edu.mt.gov.br",
    email_escola: "escola.15300@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE SANTA ROSA",
    funcao: "SECRETÁRIO",
    nome: "Flaviane Leite da Silva Cassia",
    contato: "(65) 99917 7603",
    email: "flaviane.cassia@edu.mt.gov.br",
    email_escola: "escola.15300@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE 15 DE JUNHO",
    funcao: "DIRETOR",
    nome: "Leide Carla Costa de Souza ",
    contato: "(65) 99967 7012",
    email: "leide.costa@edu.mt.gov.br",
    email_escola: "escola.15261@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE 15 DE JUNHO",
    funcao: "SECRETÁRIO",
    nome: "Fernando Costa Pedroso",
    contato: "(65) 99944 3560",
    email: "fernando.c.pedroso@edu.mt.gov.br",
    email_escola: "escola.15261@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE 15 DE JUNHO",
    funcao: "COORDENADOR",
    nome: "Fernanda Shono da Silva L. Rezende ",
    contato: "(65) 99915 7801",
    email: "fernanda.rezende@edu.mt.gov.br",
    email_escola: "escola.15261@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE MIGUEL BARBOSA",
    funcao: "DIRETOR",
    nome: "Percilia de Oliveira ",
    contato: "(65) 99644 3557",
    email: "percilia.oliveira@edu.mt.gov.br",
    email_escola: "escola.15237@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE MIGUEL BARBOSA",
    funcao: "SECRETÁRIO",
    nome: "Nilton Flávio Zancanaro",
    contato: "(65) 99938 2202",
    email: "nilton.zancanaro@edu.mt.gov.br",
    email_escola: "escola.15237@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE MIGUEL BARBOSA",
    funcao: "COORDENADOR",
    nome: "Luana Catarine Ferrari ",
    contato: "(65) 99619 7388",
    email: "luana.ferrari@edu.mt.gov.br",
    email_escola: "escola.15237@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE MIGUEL BARBOSA",
    funcao: "COORDENADOR",
    nome: "Verônica Cecília Lacerda da S. Borges ",
    contato: "(65) 99638 1663",
    email: "veronica.borges@edu.mt.gov.br",
    email_escola: "escola.15237@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE LOURENÇO PERUCHI",
    funcao: "DIRETOR",
    nome: "Rosiclea Camilo",
    contato: "(65) 99928 1599",
    email: "rosiclea.camilo@edu.mt.gov.br",
    email_escola: "escola.15253@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE LOURENÇO PERUCHI",
    funcao: "SECRETÁRIO",
    nome: "Clodoaldo Costa de Souza",
    contato: "(65) 99609 0345",
    email: "clodoaldo.costa@edu.mt.gov.br",
    email_escola: "escola.15253@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE LOURENÇO PERUCHI",
    funcao: "COORDENADOR",
    nome: "Kátia Santos ",
    contato: "(65) 99998 7024",
    email: "katia.santos@edu.mt.gov.br",
    email_escola: "escola.15253@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE DEPUTADO BERTOLDO FREIRE",
    funcao: "DIRETOR",
    nome: "Ronaldo Floreano dos Santos ",
    contato: "(65) 99643 2423",
    email: "ronaldo.floreano@edu.mt.gov.br",
    email_escola: "escola.15210@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE DEPUTADO BERTOLDO FREIRE",
    funcao: "SECRETÁRIO",
    nome: "Catia Cristina da Silva Oliveira ",
    contato: "(65) 99690 2230",
    email: "catia.silva@edu.mt.gov.br",
    email_escola: "escola.15210@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE DEPUTADO BERTOLDO FREIRE",
    funcao: "COORDENADOR",
    nome: "Sandra Santiago Afonso ",
    contato: "(65) 99905 7610",
    email: "sandra.afonso@edu.mt.gov.br",
    email_escola: "escola.15210@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE BENTO ALEXANDRE DOS SANTOS",
    funcao: "DIRETOR",
    nome: "Schilze dos Santos ",
    contato: "(65) 99922 0137",
    email: "schilze.santos@edu.mt.gov.br",
    email_escola: "escola.15288@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE BENTO ALEXANDRE DOS SANTOS",
    funcao: "SECRETÁRIO",
    nome: "Giseli de Souza Gomes ",
    contato: "(65) 99925 5240",
    email: "giseli.gomes@edu.mt.gov.br",
    email_escola: "escola.15288@edu.mt.gov.br",
  },
  {
    cidade: "QUATRO MARCOS",
    escola: "EE BENTO ALEXANDRE DOS SANTOS",
    funcao: "COORDENADOR",
    nome: "Maria Eliza dos Santos Massoni",
    contato: "(65) 99664 6661",
    email: "maria.massoni@edu.mt.gov.br",
    email_escola: "escola.15288@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE JOÃO SATO",
    funcao: "DIRETOR",
    nome: "Juliana Alves de Jesus Quevedo ",
    contato: "(65) 99986 1240",
    email: "juliana.quevedo@edu.mt.gov.br",
    email_escola: "escola.16560@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE JOÃO SATO",
    funcao: "SECRETÁRIO",
    nome: "Lucilêda Moreira Rios",
    contato: "(65) 99631 2266",
    email: "lucileda.rios@edu.mt.gov.br",
    email_escola: "escola.16560@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE JOÃO SATO",
    funcao: "COORDENADOR",
    nome: "Auleni Dias Freitas de Moraes ",
    contato: "(65) 99622 0042",
    email: "auleni.moraes@edu.mt.gov.br",
    email_escola: "escola.16560@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE NOSSA SENHORA DE FÁTIMA",
    funcao: "DIRETOR",
    nome: "Jeferson dos Santos Capelletti",
    contato: "(65) 99955 8661",
    email: "jeferson.capelletti@edu.mt.gov.br",
    email_escola: "escola.16624@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE NOSSA SENHORA DE FÁTIMA",
    funcao: "SECRETÁRIO",
    nome: "Keile Eduardo Passos",
    contato: "(65) 99992 5596",
    email: "keile.passos@edu.mt.gov.br",
    email_escola: "escola.16624@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE NOSSA SENHORA DE FÁTIMA",
    funcao: "COORDENADOR",
    nome: "Gerson Cardoso Kempe ",
    contato: "(65) 98408 1740",
    email: "gerson.kempe@edu.mt.gov.br",
    email_escola: "escola.16624@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE NOSSA SENHORA DE FÁTIMA",
    funcao: "COORDENADOR",
    nome: "Luciana Alves de Oliveira",
    contato: "(65) 99605 1571",
    email: "luciana.a.oliveira@edu.mt.gov.br",
    email_escola: "escola.16624@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE PRESIDENTE TANCREDO NEVES",
    funcao: "DIRETOR",
    nome: "Alessandra Xavier Brito Palermo ",
    contato: "(65) 99903 5045",
    email: "alessandra.palermo@edu.mt.gov.br",
    email_escola: "escola.16594@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE PRESIDENTE TANCREDO NEVES",
    funcao: "SECRETÁRIO",
    nome: "Euquiria F. Nobokite Guimaraes ",
    contato: "(65) 99617 8689",
    email: "euquiria.guimaraes@edu.mt.gov.br",
    email_escola: "escola.16594@edu.mt.gov.br",
  },
  {
    cidade: "ARAPUTANGA",
    escola: "EE PRESIDENTE TANCREDO NEVES",
    funcao: "COORDENADOR",
    nome: "Isabel Angelina Agustini ",
    contato: "(65) 99905 7725",
    email: "isabel.agustini@edu.mt.gov.br",
    email_escola: "escola.16594@edu.mt.gov.br",
  },
  {
    cidade: "INDIAVAÍ",
    escola: "EE PAULINO MODESTO",
    funcao: "DIRETOR",
    nome: "Daise Alves Ferreira ",
    contato: "(65) 99965-4954",
    email: "daise.ferreira@edu.mt.gov.br",
    email_escola: "escola.16640@edu.mt.gov.br",
  },
  {
    cidade: "INDIAVAÍ",
    escola: "EE PAULINO MODESTO",
    funcao: "SECRETÁRIO",
    nome: "Devanir",
    contato: "(65) 99969 4871",
    email_escola: "escola.16640@edu.mt.gov.br",
  },
  {
    cidade: "RESERVA DO CABAÇAL",
    escola: "EE PROF. DEMÉTRIO PEREIRA",
    funcao: "DIRETOR",
    nome: "Érica Venancio Alves ",
    contato: "(65) 99683 5489",
    email: "erica.alves@edu.mt.gov.br",
    email_escola: "escola.16632@edu.mt.gov.br",
  },
  {
    cidade: "RESERVA DO CABAÇAL",
    escola: "EE PROF. DEMÉTRIO PEREIRA",
    funcao: "SECRETÁRIO",
    nome: "Marcia Ferreira da Silva ",
    contato: "(65) 99949 9204",
    email: "marcia.silva.1@edu.mt.gov.br",
    email_escola: "escola.16632@edu.mt.gov.br",
  },
  {
    cidade: "RESERVA DO CABAÇAL",
    escola: "EE PROF. DEMÉTRIO PEREIRA",
    funcao: "COORDENADOR",
    nome: "Arliane Antunes Otone ",
    contato: "(65) 99229 2510",
    email: "arliane.otone@edu.mt.gov.br",
    email_escola: "escola.16632@edu.mt.gov.br",
  },
  {
    cidade: "RESERVA DO CABAÇAL",
    escola: "EE PROF. DEMÉTRIO PEREIRA",
    funcao: "COORDENADOR",
    nome: "Marilene de Souza Camargo ",
    contato: "(65) 99607 8503",
    email: "marilene.camargo@edu.mt.gov.br",
    email_escola: "escola.16632@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE SÃO GERALDO",
    funcao: "DIRETOR",
    nome: "Natalia Stella",
    contato: "(65) 99917 8251",
    email_escola: "escola.16322@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE SÃO GERALDO",
    funcao: "SECRETÁRIO",
    nome: "Rozelino Mendes Surubi",
    contato: "(65) 99966 1900",
    email: "rozelino.surubi@edu.mt.gov.br",
    email_escola: "escola.16322@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE SÃO GERALDO",
    funcao: "COORDENADOR",
    nome: "Aleandro de Souza",
    contato: "(65) 99964 9526",
    email: "aleandro.souza@edu.mt.gov.br",
    email_escola: "escola.16322@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE 13 DE MAIO",
    funcao: "DIRETOR",
    nome: "Cátia Meschiari dos Santos",
    contato: "(65) 99649 6967",
    email: "catia.santos@edu.mt.gov.br",
    email_escola: "escola.16314@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE 13 DE MAIO",
    funcao: "SECRETÁRIO",
    nome: "Eryck Thaygor Pereira da Silva",
    contato: "(65) 99922 2141",
    email: "eryck.silva@edu.mt.gov.br",
    email_escola: "escola.16314@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE 13 DE MAIO",
    funcao: "COORDENADOR",
    nome: "Jane de Fátima Guerreiro",
    contato: "(65) 99954 8813",
    email: "jane.guerreiro@edu.mt.gov.br",
    email_escola: "escola.16314@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE 13 DE MAIO",
    funcao: "COORDENADOR",
    nome: "Valtair Guedes",
    contato: "(65) 99913 3761",
    email: "valtair.guedes@edu.mt.gov.br",
    email_escola: "escola.16314@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE INDÍGENA CHIQUITANO",
    funcao: "DIRETOR",
    nome: "José de Arruda Mendes",
    contato: "(65) 99921 0257",
    email: "jose.mendes@edu.mt.gov.br",
    email_escola: "escola.109444@edu.mt.gov.br",
  },
  {
    cidade: "PORTO ESPERIDIÃO",
    escola: "EE INDÍGENA JOSÉ TURÍBIO",
    funcao: "DIRETOR",
    nome: "Saturnina Urupe Chue ",
    contato: "(65) 99980 2093",
    email: "saturnina.chue@edu.mt.gov.br",
    email_escola: "escola.154989@edu.mt.gov.br",
  },
  {
    cidade: "RIO BRANCO",
    escola: "EE DEPUTADO FRANCISCO EDUARDO RANGEL TORRES",
    funcao: "DIRETOR",
    nome: "Iracema de Souza ",
    contato: "(65) 99642 7724",
    email: "iracema.souza@edu.mt.gov.br",
    email_escola: "escola.11886@edu.mt.gov.br",
  },
  {
    cidade: "RIO BRANCO",
    escola: "EE DEPUTADO FRANCISCO EDUARDO RANGEL TORRES",
    funcao: "SECRETÁRIO",
    nome: "Adriany Sabrine F. do Nascimento ",
    contato: "(65) 99600 7328",
    email: "adriany.ferreira@edu.mt.gov.br",
    email_escola: "escola.11886@edu.mt.gov.br",
  },
  {
    cidade: "RIO BRANCO",
    escola: "EE DEPUTADO FRANCISCO EDUARDO RANGEL TORRES",
    funcao: "COORDENADOR",
    nome: "Mônica Valéria Ferrari Santos ",
    contato: "(65) 99632 5186",
    email: "monica.santos@edu.mt.gov.br",
    email_escola: "escola.11886@edu.mt.gov.br",
  },
  {
    cidade: "RIO BRANCO",
    escola: "EE DEPUTADO FRANCISCO EDUARDO RANGEL TORRES",
    funcao: "COORDENADOR",
    nome: "Silvania Alves dos Reis ",
    contato: "(65) 99637 1325",
    email: "silvania.reis@edu.mt.gov.br",
    email_escola: "escola.11886@edu.mt.gov.br",
  },
  {
    cidade: "SALTO DO CÉU",
    escola: "EE DEPUTADO FRANCISCO VILLANOVA",
    funcao: "DIRETOR",
    nome: "Allisom Cordeiro Bessa de Oliveira ",
    contato: "(65) 98466 2995",
    email: "allison.oliveira@edu.mt.gov.br",
    email_escola: "escola.11843@edu.mt.gov.br",
  },
  {
    cidade: "SALTO DO CÉU",
    escola: "EE DEPUTADO FRANCISCO VILLANOVA",
    funcao: "SECRETÁRIO",
    nome: "Elen Rosa Córes ",
    contato: "(65) 99933 8541",
    email: "elen.cores@edu.mt.gov.br",
    email_escola: "escola.11843@edu.mt.gov.br",
  },
  {
    cidade: "SALTO DO CÉU",
    escola: "EE DEPUTADO FRANCISCO VILLANOVA",
    funcao: "COORDENADOR",
    nome: "Francisca Neta Nunes",
    contato: "(65) 99905 7168",
    email: "francisca.nunes@edu.mt.gov.br",
    email_escola: "escola.11843@edu.mt.gov.br",
  },
  {
    cidade: "SALTO DO CÉU",
    escola: "EE DEPUTADO FRANCISCO VILLANOVA",
    funcao: "COORDENADOR",
    nome: "Karine Marreiro Soares",
    contato: "(65) 99641 4128",
    email: "karine.soares@edu.mt.gov.br",
    email_escola: "escola.11843@edu.mt.gov.br",
  },
  {
    cidade: "SALTO DO CÉU",
    escola: "EE VILA PROGRESSO",
    funcao: "DIRETOR",
    nome: "Valdeci Jorge carmo",
    contato: "(65) 99996 4992",
    email: "valdeci.carmo@edu.mt.gov.br",
    email_escola: "escola.11851@edu.mt.gov.br",
  },
  {
    cidade: "SALTO DO CÉU",
    escola: "EE VILA PROGRESSO",
    funcao: "SECRETÁRIO",
    nome: "Mário Angelo Frade Monteiro",
    contato: "(65) 99926 2038",
    email: "mario.monteiro@edu.mt.gov.br",
    email_escola: "escola.11851@edu.mt.gov.br",
  },
  {
    cidade: "LAMBARÍ D'OESTE",
    escola: "EE PADRE JOSÉ DE ANCHIETA",
    funcao: "DIRETOR",
    nome: "Claudio Guilherme de Sene",
    contato: "(65) 99952 8483",
    email: "claudio.sene@edu.mt.gov.br",
    email_escola: "escola.11851@edu.mt.gov.br",
  },
  {
    cidade: "LAMBARÍ D'OESTE",
    escola: "EE PADRE JOSÉ DE ANCHIETA",
    funcao: "SECRETÁRIO",
    nome: "Lubia Martins da Cruz    ",
    contato: "(65) 99624 6061",
    email: "lubia.mendes@edu.mt.gov.br",
    email_escola: "escola.11894@edu.mt.gov.br",
  },
  {
    cidade: "GLÓRIA D'OESTE",
    escola: "EE JOSÉ BEJO",
    funcao: "DIRETOR",
    nome: "Halassi Nunes dos Santos  ",
    contato: "(65) 99613 4630",
    email: "halassi.santos@edu.mt.gov.br",
    email_escola: "escola.71790@edu.mt.gov.br",
  },
  {
    cidade: "GLÓRIA D'OESTE",
    escola: "EE JOSÉ BEJO",
    funcao: "SECRETÁRIO",
    nome: "Elizangela Neves ",
    contato: "(65) 99945 5282",
    email: "elizangela.neves@edu.mt.gov.br",
    email_escola: "escola.71790@edu.mt.gov.br",
  },
  {
    cidade: "GLÓRIA D'OESTE",
    escola: "EE JOSÉ BEJO",
    funcao: "COORDENADOR",
    nome: "Alex Carbonel Pereira",
    contato: "(65) 99954 4716",
    email: "alex.pereira@edu.mt.gov.br",
    email_escola: "escola.71790@edu.mt.gov.br",
  },
  {
    cidade: "GLÓRIA D'OESTE",
    escola: "EE RUI BARBOSA",
    funcao: "DIRETOR",
    nome: "Fabiana Pardini",
    contato: "(65) 99908 1334",
    email: "fabiana.alves@edu.mt.gov.br",
    email_escola: "escola.71803@edu.mt.gov.br",
  },
  {
    cidade: "GLÓRIA D'OESTE",
    escola: "EE RUI BARBOSA",
    funcao: "SECRETÁRIO",
    nome: "Nilton Aparecido Martins",
    contato: "(65) 99622 5853",
    email: "nilton.martins@edu.mt.gov.br",
    email_escola: "escola.71803@edu.mt.gov.br",
  },
  {
    cidade: "GLÓRIA D'OESTE",
    escola: "EE RUI BARBOSA",
    funcao: "COORDENADOR",
    nome: "Alexandra Bressanin",
    contato: "(65) 99651 9230 ",
    email: "alexandra.bressanin@edu.mt.gov.br",
    email_escola: "escola.71803@edu.mt.gov.br",
  },
];
